name: Metrics
on:
  # Schedule daily updates
  # schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      # - uses: lowlighter/metrics@latest
      - uses: flashsherlock/metrics@master
        with:
            config_timezone: Asia/Shanghai
            filename: metrics.classic.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: header, repositories
            repositories_skipped: |
              @use.patterns

              # Skip a specific repository
              -flashsherlock/flashsherlock.github.io
              -flashsherlock/github-slideshow
              -flashsherlock/learnR
              -flashsherlock/metrics
              -flashsherlock/rsatoolbox
              -flashsherlock/Inquisit-Web-BNUPSY
              -flashsherlock/WebBasedPsychologyProgram
            plugin_lines: yes
            plugin_languages: yes
            plugin_languages_sections: most-used #, recently-used
            plugin_languages_indepth: yes
            plugin_languages_details: lines, bytes-size
            plugin_languages_limit: 4
            plugin_languages_ignored: html, javascript, css, SCSS, M, Ruby
            plugin_languages_analysis_timeout: 60
            plugin_languages_analysis_timeout_repositories: 0
            plugin_languages_recent_load: 200
            plugin_languages_recent_days: 14